name: GitHub-Profile-3D-Contrib

on:
  schedule: # Roda em horários agendados
    - cron: "0 18 * * *" # Exemplo: todos os dias às 18:00 UTC (15:00 no seu fuso -03:00)
  workflow_dispatch: # Permite rodar manualmente pela aba Actions do GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3 # Usando v3 para checkout
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1 # Versão mais recente da action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }} # Usa o dono do repositório (seu username)
          MAX_REPOS: "100" # Opcional: número de repositórios a considerar
          # Você pode adicionar mais customizações aqui conforme a documentação da action
          # https://github.com/yoshi389111/github-profile-3d-contrib
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A .
          # Verifica se há mudanças antes de tentar commitar
          if ! git diff --staged --quiet; then
            git commit -m "chore: update 3D contribution graph"
            git push
          else
            echo "No changes to commit for 3D contribution graph."
          fi
